---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.podname }}-admin-event
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
data:
  recovery_tag: |-
    {{ .Values.admin.recovery | default "none" | sha256sum }}
  cmd_args: |-
    {{- if (.Values.admin.recovery) }}
    {{- $vals := (split ":" .Values.admin.recovery) }}
    node={{ $vals._1 }}
    {{- end }}
  {{- if .Values.admin.pwChangeSecret }}
  pw_change_secret: {{ default "" .Values.admin.pwChangeSecret }}
  {{- end }}
