{{- if ne (.Values.cluster_type) "simplex" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name.podname }}-admin-secrets
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-failed
type: Opaque
data:
  redis-password: {{ randAlphaNum 64 | b64enc | quote }}
{{ end }}
