---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.podname }}-mariadb-cluster
  labels:
    {{- include "cmdb-mariadb.labels" . | indent 4 }}
data:
  cluster.env: |-
    INSTALLED_CLUSTER_TYPE={{ .Values.cluster_type }}
  {{- if eq .Values.cluster_type "simplex" }}
    CLUSTER_SIZE=1
    HEURISTIC_RECOVER={{ default "none" .Values.mariadb.heuristic_recover }}
  {{- else }}
    CLUSTER_SIZE={{ .Values.mariadb.count }}
    HEURISTIC_RECOVER={{ default "rollback" .Values.mariadb.heuristic_recover }}
  {{- end }}
    MAXSCALE_SIZE={{ .Values.maxscale.count }}
    CLEAN_LOG_INTERVAL={{ .Values.mariadb.clean_log_interval }}
    USE_TLS={{ .Values.mariadb.use_tls }}
    PRESERVE_PVC={{ .Values.mariadb.persistence.preserve_pvc }}
    MAX_NODE_WAIT={{ .Values.max_node_wait }}
    MAXSCALE_USER={{ .Values.maxscale.maxscale_user }}
    REPLICATION_USER={{ .Values.mariadb.repl_user }}
  {{- if .Values.mariadb.repl_use_ssl }}
    REPLICATION_SSL=on
  {{- end }}
  {{- if .Values.mariadb.metrics.enabled }}
    MYSQL_METRICS_USER={{ .Values.mariadb.metrics.user }}
  {{- end }}
  {{- if .Values.admin.debug }}
    DB_DEBUG=yes
  {{- end }}

