{{- if .Values.cbur.enabled }}
apiVersion: "cbur.bcmt.local/v1"
kind: BrPolicy
metadata:
  name: {{ .Values.name.podname }}-mariadb
  labels:
    {{- include "cmdb-mariadb.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name.podname }}
      csf-subcomponent: mariadb
  k8sobjects:
  - object-type: [secrets]
    match-criteria: name
    label-key:
    match-string: secretstore-mariadb-mariadb
  - object-type: [secrets]
    match-criteria: name
    label-key:
    match-string: secretstore-mariadb-token 
  volumes:
  {{- if and (.Values.mariadb.persistence.backup) (.Values.mariadb.persistence.backup.enabled) }}
  - backupdir
  {{- else }}
  - datadir/backup
  {{- end }}
  backend:
    mode: "{{ .Values.cbur.backendMode }}"
  cronSpec: "{{ .Values.cbur.cronSpec }}"
  k8sType: statefulset
  {{- if eq .Values.cluster_type "galera" }}
  brOption: 2
  {{- else }}
  brOption: 1
  {{- end }}
  maxiCopy: {{ .Values.cbur.maxiCopy}}
  hooks:
  - name: mariadb
    commands:
      preBackupCmd: ["sh", "-c", "rm -rf {{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/*; /usr/bin/mariadb_db_backup --backup --keystore --dir={{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/tmp --file {{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/{{ .Values.name.podname}}-$(date +%Y%m%d_%H%M%S)-backup.tgz | tee /var/log/mariadb/mariadb_db_backup.out"]
      postBackupCmd: ["sh", "-c", "echo post-backup"]
      preRestoreCmd: ["sh", "-c", "rm -rf {{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/*"]
      {{- if eq .Values.cluster_type "galera" }}
      {{- if .Values.cbur.jobhookenable }}
      postRestoreCmd: ["sh", "-c", "echo post-restore"]
      {{- else }}
      postRestoreCmd: ["sh", "-c", "/usr/bin/mariadb_db_backup --restore --all --nostart --keystore --dir={{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/tmp --file {{ default "/mariadb/archive" .Values.mariadb.persistence.backup.dir }}/*backup.tgz | tee /var/log/mariadb/mariadb_db_restore.out"]
      {{- end }}
      {{- else }}
      postRestoreCmd: ["sh", "-c", "/usr/bin/mariadb_db_backup --restore --all --keystore --dir={{ default "/mariadb/backup" .Values.mariadb.persistence.backup.dir }}/tmp --file {{ default "/mariadb/archive" .Values.mariadb.persistence.backup.dir }}/*backup.tgz | tee /var/log/mariadb/mariadb_db_restore.out; sleep 60"]
      {{- end }}
{{- end }}
