{{- if gt (int .Values.maxscale.count) 0 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "cmdb.fullname" . }}-maxscale
  labels:
    {{- include "cmdb-maxscale.labels" . | indent 4 }}
    
spec:
  serviceName: {{ template "cmdb.fullname" . }}
  replicas: {{ .Values.maxscale.count }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "cmdb-maxscale.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "cmdb-maxscale.labels" . | indent 8 }}
        type: maxscale
    {{- if .Values.admin.configAnnotation }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/maxscale-config-configmap.yaml") . | sha256sum }}
    {{- end }}
    spec:
      securityContext:
      {{- if .Values.rbac_enabled }}
        runAsUser: 1772
        runAsGroup: 1772
      serviceAccountName: {{ template "cmdb.fullname" . }}-le
      {{- end }}
      initContainers:
      - name: "maxscaleinit-keystore"
        {{- include "cmdb-admin.image" . | indent 8 }}
        command:
          - bash
          - "-c"
          - |
            typeset -i idx=0
            while true; do
              pod={{ template "cmdb.fullname" . }}-mariadb-$(( idx % CLUSTER_SIZE ))
              echo "Attempting to obtain keystore from $pod"
              kubectl cp -n ${K8S_NAMESPACE} $pod:/mariadb/data/.keystore /keydir/.keystore -c mariadb >/dev/null && \
              kubectl cp -n ${K8S_NAMESPACE} $pod:/mariadb/data/.login.cnf /keydir/.login.cnf -c mariadb >/dev/null && {
                  rm -f /keydir/.wait-pw-import
                  kubectl cp -n ${K8S_NAMESPACE} $pod:/mariadb/data/.wait-pw-import /keydir/.wait-pw-import -c mariadb >/dev/null
                  [ ! -f /keydir/.wait-pw-import ] && [ -f /keydir/.keystore ] && [ -f /keydir/.login.cnf ] && exit 0
              }
              (( idx++ ))
              sleep 1
            done
            exit 1
        env:
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: CLUSTER_SIZE
          value: "{{ .Values.mariadb.count }}"
        volumeMounts:
        - name: keydir
          mountPath: /keydir
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      - name: "maxscaleinit-config"
        {{- include "cmdb-maxscale.image" . | indent 8 }}
        env:
        command:
          - bash
          - "-c"
          - |
            cp /import-maxscale-cm/maxscale.site /import/
            cp /import-maxscale-cm/*.sql /import/ 2>/dev/null
            cp /import-mariadb-cm/mysqld.site /import/
            sed -i -e '$a\' /import/*
        volumeMounts:
        - name: import
          mountPath: /import
        - name: import-maxscale-cm
          mountPath: /import-maxscale-cm
        - name: import-mariadb-cm
          mountPath: /import-mariadb-cm
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi

      containers:
      - name: maxscale
        {{- include "cmdb-maxscale.image" . | indent 8 }}
        ports:
      {{- if .Values.maxscale.listeners }}
        - containerPort: {{ default 3306 .Values.maxscale.listeners.rwSplit }}
          name: mysql
        {{- if gt (default 0 (int .Values.maxscale.listeners.readOnly)) 0 }}
        - containerPort: {{ .Values.maxscale.listeners.readOnly }}
          name: mysql-readonly
        {{- end }}
        {{- if gt (default 0 (int .Values.maxscale.listeners.masterOnly)) 0 }}
        - containerPort: {{ .Values.maxscale.listeners.masterOnly }}
          name: mysql-mstronly
        {{- end }}
        {{- if or (.Values.maxscale.metrics.enabled) (gt (default 0 (int .Values.maxscale.listeners.maxInfo)) 0) }}
        - containerPort: {{ default 8003 .Values.maxscale.listeners.maxInfo }}
          name: maxscale-info
        {{- end }}
      {{- else }}
        - containerPort: 3306
          name: mysql
      {{- end }}
        - containerPort: {{ .Values.services.maxscale.port }}
          name: maxscale
        env:
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster_name | default .Release.Name | trunc 32 }}"
        - name: MYIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KEYSTORE_DIR
          value: "/.keydir"
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "cmdb-admin.service" . | indent 8 }}

      {{- if .Values.maxscale.listeners }}
        {{- if .Values.maxscale.listeners.rwSplit }}
        - name: MAXSCALE_RW_PORT
          value: {{ .Values.maxscale.listeners.rwSplit | quote }}
        {{- end }}
        {{- if .Values.maxscale.listeners.readOnly }}
        - name: MAXSCALE_RO_PORT
          value: {{ .Values.maxscale.listeners.readOnly | quote }}
        {{- end }}
        {{- if .Values.maxscale.listeners.masterOnly }}
        - name: MAXSCALE_MSTR_PORT
          value: {{ .Values.maxscale.listeners.masterOnly | quote }}
        {{- end }}
        {{- if or (.Values.maxscale.metrics.enabled) (.Values.maxscale.listeners.maxInfo) }}
        - name: MAXSCALE_INFO_PORT
          value: {{ default 8003 .Values.maxscale.listeners.maxInfo | quote }}
        {{- end }}
      {{- end }}
       
      {{- $ctx := . }}
      {{- with .Values.geo_redundancy }}
        {{- if .enabled }}
        - name: DATACENTER_REMOTE_HOST
          value: {{ template "cmdb.fullname" $ctx }}-maxscale-{{ .remote.name }}
        - name: DATACENTER_REMOTE_MASTER
          value: {{ template "cmdb.fullname" $ctx }}-master-{{ .remote.name }}
        - name: DATACENTER_LAG_THRESHOLD
          value: {{ .lag_threshold | quote }}
        - name: DATACENTER_SLAVE_PURGE_INTERVAL
          value: {{ .slave_purge_interval | quote }}
        {{- end }}
      {{- end }}

        volumeMounts:
        {{- if and (.Values.mariadb.use_tls) (.Values.mariadb.certificates.secret) }}
        - name: mdb-certificates
          readOnly: true
          mountPath: "/etc/.certificates"
        {{- end }}
        - name: cluster-cm
          mountPath: /chart
        - name: import
          mountPath: /import
        - name: keydir
          mountPath: /.keydir
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              /usr/bin/maxscale_adm --check-sanity --timeout=5
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 6
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              /usr/bin/maxscale_adm  --check-ready --timeout=5
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 6
          failureThreshold: 4
        resources:
{{ toYaml .Values.maxscale.resources | indent 10 }}

      - name: leader-elector
        {{- include "maxscale-elector.image" . | indent 8 }}
        ports:
        - name: leader-query
          containerPort: 4040
        args: [ "--election={{ template "cmdb.fullname" . }}-leader --election-namespace={{ .Release.Namespace }} --ttl=5s --http=0.0.0.0:4040" ]
        resources:
{{ toYaml .Values.maxscale.elector.resources | indent 10 }}

      {{- if .Values.maxscale.metrics.enabled }}
      - name: metrics
        {{- include "maxscale-metrics.image" . | indent 8 }}
        ports:
        - name: mxs-metrics
          containerPort: {{ .Values.services.maxscale.exporter_port }}
        args: [ "-address=localhost:{{ default 8003 .Values.maxscale.listeners.maxInfo }}", "-port={{ .Values.services.maxscale.exporter_port }}" ]
        volumeMounts:
        - name: metrics
          mountPath: /metrics
        resources:
{{ toYaml .Values.maxscale.metrics.resources | indent 10 }}
      {{- end }}

      terminationGracePeriodSeconds: {{ default 30 .Values.maxscale.terminationGracePeriodSeconds }}

      volumes:
      {{- if and (.Values.mariadb.use_tls) (.Values.mariadb.certificates.secret) }}
      - name: mdb-certificates
        secret:
          secretName: {{ .Values.mariadb.certificates.secret }}
      {{- end }}

      - name: cluster-cm
        configMap:
          name: {{ template "cmdb.fullname" . }}-mariadb-cluster
      - name: import
        emptyDir: {}
      - name: import-maxscale-cm
        configMap:
          name: {{ template "cmdb.fullname" . }}-maxscale-config
      - name: import-mariadb-cm
        configMap:
          name: {{ template "cmdb.fullname" . }}-mariadb-config
      - name: keydir
        emptyDir: {}
      {{- if .Values.maxscale.metrics.enabled }}
      - name: metrics
        emptyDir:
          medium: Memory
      {{- end }}

    {{- if .Values.maxscale.tolerations }}
      tolerations:
{{ toYaml .Values.maxscale.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.maxscale.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.maxscale.nodeSelector | indent 8 }}
    {{- end }}
      affinity:
      {{- if .Values.maxscale.nodeAffinity.enabled }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.maxscale.nodeAffinity.key }}
                operator: In
                values:
                - {{ quote .Values.maxscale.nodeAffinity.value }}
      {{- end }}
        podAntiAffinity:
        ## Unset value uses soft for backwards-compatibility
        {{- if eq (default "soft" .Values.nodeAntiAffinity) "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "cmdb.fullname" . }}
              - key: type
                operator: In
                values:
                - mariadb
                - maxscale
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
        {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "cmdb.fullname" . }}
                - key: type
                  operator: In
                  values:
                  - mariadb
                  - maxscale
              topologyKey: "kubernetes.io/hostname"
        {{- end }}
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "cmdb.fullname" . }}
                - key: type
                  operator: In
                  values:
                  - mariadb
                  - maxscale
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
{{- end }}
