---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cmdb.fullname" . }}-maxscale-config
  labels:
    {{- include "cmdb-maxscale.labels" . | indent 4 }}
data:
  maxscale.site: |-
{{- if .Values.maxscale.maxscale_site_conf }}
{{ .Values.maxscale.maxscale_site_conf | indent 4 }}
{{- end }}
    [maxscale]
    admin_host = ::
    admin_port = {{ .Values.services.maxscale.port }}
{{- if and (.Values.mariadb.use_tls) (.Values.mariadb.certificates.secret) }}
    [SSL]
    ssl=required
    ssl_cert=/etc/my.cnf.d/ssl/{{ .Values.mariadb.certificates.client_cert }}
    ssl_key=/etc/my.cnf.d/ssl/{{ .Values.mariadb.certificates.client_key }}
    ssl_ca_cert=/etc/my.cnf.d/ssl/{{ .Values.mariadb.certificates.client_ca_cert }}
    ssl_cert_verify_depth=9
    ssl_version=MAX
{{- end }}
{{- if .Values.maxscale.sql.promotion }}
  promotion.sql: |-
{{- range .Values.maxscale.sql.promotion }}
    {{ . | trimSuffix ";" }};
{{- end }}
{{- end }}
{{- if .Values.maxscale.sql.demotion }}
  demotion.sql: |-
{{- range .Values.maxscale.sql.demotion }}
    {{ . | trimSuffix ";" }};
{{- end }}
{{- end }}

