---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mysql.name | default (printf "%s-mysql" (include "cmdb.fullname" .)) | quote }}
  labels:
  # Service provided by MaxScale acting as a proxy or
  # by MariaDB itself if MaxScale not in use
  {{- if gt (int .Values.maxscale.count) 0 }}
    {{- include "cmdb-maxscale.labels" . | indent 4 }}
  {{- else }}
    {{- include "cmdb-mariadb.labels" . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.mysql.type }}
  ports:
# Include configured listener ports, if maxscale is used
{{- if and (gt (int .Values.maxscale.count) 0) .Values.maxscale.listeners }}
  - name: mysql
    port: {{ default 3306 .Values.maxscale.listeners.rwSplit }}
    targetPort: mysql
    {{- if and (eq .Values.services.mysql.type "NodePort") (.Values.services.mysql.nodePort) }}
    nodePort: {{ .Values.services.mysql.nodePort }}
    {{- end }}
  {{- if gt (default 0 (int .Values.maxscale.listeners.readOnly)) 0 }}
  - name: mysql-readonly
    port: {{ .Values.maxscale.listeners.readOnly }}
    targetPort: mysql-readonly
    {{- if and (eq .Values.services.mysql.type "NodePort") (.Values.services.mysql.nodePort_readonly) }}
    nodePort: {{ .Values.services.mysql.nodePort_readonly }}
    {{- end }}
  {{- end }}
  {{- if gt (default 0 (int .Values.maxscale.listeners.masterOnly)) 0 }}
  - name: mysql-mstronly
    port: {{ .Values.maxscale.listeners.masterOnly }}
    targetPort: mysql-mstronly
    {{- if and (eq .Values.services.mysql.type "NodePort") (.Values.services.mysql.nodePort_mstronly) }}
    nodePort: {{ .Values.services.mysql.nodePort_mstronly }}
    {{- end }}
  {{- end }}
{{- else }}
  - name: mysql
    port: 3306
    targetPort: mysql
    {{- if and (eq .Values.services.mysql.type "NodePort") (.Values.services.mysql.nodePort) }}
    nodePort: {{ .Values.services.mysql.nodePort }}
    {{- end }}
{{- end }}
  selector:
  # Point the mysql service at maxscale, if used
  {{- if gt (int .Values.maxscale.count) 0 }}
    {{- include "cmdb-maxscale.labels" . | indent 4 }}
    type: maxscale
  {{- else }}
    {{- include "cmdb-mariadb.labels" . | indent 4 }}
    type: mariadb
  {{- end }}

