{{- if not (eq (default "enable" .Values.hooks.postInstallJob) "disable") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name.podname }}-post-install
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.deletePolicy | quote }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "cmdb-admin.labels" . | indent 8 }}
        type: admin
    spec:
      {{- if and (.Values.rbac_enabled) (eq (.Values.cluster_type) "simplex") }}
      serviceAccountName: {{ .Values.name.podname }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: post-install-admin
        {{- include "cmdb-admin.image" . | indent 8 }}
        args: [ "install" ]
        env:
        - name: CLUSTER_TYPE
          value: "{{ .Values.cluster_type }}"
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster_name | default .Release.Name | trunc 32 }}"
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ .Values.name.podname }}
        - name: K8S_PREFIX
          value: {{ .Values.name.podname }}
        - name: HOOK_TYPE
          value: "post"
        {{- if gt (int .Values.admin.postInstallTimeout) 0 }}
        - name: HOOK_TIMEOUT
          value: "{{ .Values.admin.postInstallTimeout }}"
        {{- end }}
        {{- if and .Values.admin.debug (gt (int (default '0' .Values.admin.jobDelay)) 0) }}
        - name: HOOK_DELAY
          value: "{{ .Values.admin.jobDelay }}"
        {{- end }}
        {{- if eq (default "no" .Values.admin.quickInstall) "yes" }}
        - name: QUICK_INSTALL
          value: "yes"
        {{- end }}
        {{- include "cmdb-admin.service" . | indent 8 }}
        volumeMounts:
        - name: cluster-cm
          mountPath: /chart
        - name: event-cm
          mountPath: /event
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
      volumes:
      - name: cluster-cm
        configMap:
          name: {{ .Values.name.podname }}-mariadb-cluster
      - name: event-cm
        configMap:
          name: {{ .Values.name.podname }}-admin-event
{{- end }}
