{{- if not (eq (default "enable" .Values.hooks.postDeleteJob) "disable") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name.podname }}-post-delete
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.deletePolicy | quote }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "cmdb-admin.labels" . | indent 8 }}
        type: admin
    spec:
      {{- if .Values.rbac_enabled }}
      serviceAccountName: {{ .Values.name.podname }}-delete
      {{- end }}
      restartPolicy: Never
      containers:
      - name: post-delete-admin
        {{- include "cmdb-admin.image" . | indent 8 }}
        args: [ "delete" ]
        env:
        - name: CLUSTER_TYPE
          value: "{{ .Values.cluster_type }}"
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster_name | default .Release.Name | trunc 32 }}"
        # NOTE: Since configmaps have been deleted, must explicitly set mariadb
        # and maxscale cluster sizes here
        - name: CLUSTER_SIZE
          value: "{{ .Values.mariadb.count }}"
        - name: MAXSCALE_SIZE
          value: "{{ .Values.maxscale.count }}"
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ .Values.name.podname }}
        - name: K8S_PREFIX
          value: {{ .Values.name.podname }}
        - name: HOOK_TYPE
          value: "post"
        {{- if gt (int .Values.admin.postDeleteTimeout) 0 }}
        - name: HOOK_TIMEOUT
          value: "{{ .Values.admin.postDeleteTimeout }}"
        {{- end }}
        {{- if and .Values.admin.debug (gt (int (default '0' .Values.admin.jobDelay)) 0) }}
        - name: HOOK_DELAY
          value: "{{ .Values.admin.jobDelay }}"
        {{- end }}
        - name: PRESERVE_PVC
          value: {{ .Values.mariadb.persistence.preserve_pvc | quote }}
        - name: RBAC_ENABLED
          value: {{ .Values.rbac_enabled | quote }}
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
{{- end }}
