{{/*
*
* A non-manifest helper to check that the images are of a required
* minimum version.  This prevents performing an upgrade of a chart
* while running an older version of the containers.  To be used when
* a chart expects certain functionality to exist in the container, e.g.
* in the entrypoint.
*
* NOTE: Currently only works with major.minor version of the images as
* CSF/CMDB image tags are not semVer-compliant (no .patch).
*
* NOTE: Currently checks MariaDB, Maxscale, and Admin images against same
* minimum version requirement.
*
*/}}

{{- $min_ver := ">=4.6" -}}
{{- $mdb_ver := .Values.image.mariadb.dockerTag -}}
{{- $mxs_ver := .Values.image.maxscale.dockerTag -}}
{{- $adm_ver := .Values.image.admin.dockerTag -}}

{{- $min_semver := printf "%s.0" $min_ver -}}
{{- $mdb_semver := regexReplaceAllLiteral "-.*" $mdb_ver ".0" -}}
{{- $mxs_semver := regexReplaceAllLiteral "-.*" $mxs_ver ".0" -}}
{{- $adm_semver := regexReplaceAllLiteral "-.*" $adm_ver ".0" -}}

{{- if not (semverCompare $min_semver $mdb_semver) -}}
{{- $_ := required (printf "mariadb.image.tag must be %s, is currently %s" $min_ver $mdb_ver) "" -}}
{{- else if not (semverCompare $min_semver $mxs_semver) -}}
{{- $_ := required (printf "maxscale.image.tag must be %s, is currently %s" $min_ver $mxs_ver) "" -}}
{{- else if not (semverCompare $min_semver $adm_semver) -}}
{{- $_ := required (printf "admin.image.tag must be %s, is currently %s" $min_ver $adm_ver) "" -}}
{{- end -}}
