apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    component: elasticsearch
    role: client
    release: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: elasticsearch
    role: client
    release: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: {{.Values.service.client_port}}
      protocol: TCP
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.client_nodeport))) }}
      nodePort: {{.Values.service.client_nodeport}}
      {{- end }}
