apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-discovery
  labels:
    component: elasticsearch
    role: master 
    release: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.service.type }} 
  selector:
    component: elasticsearch
    role: master 
    release: {{ .Release.Name | quote }}
  ports:
    - name: transport 
      port: {{.Values.service.master_port}}
      protocol: TCP
