{{- if .Values.searchguard.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }} 
type: Opaque
data:
  keystore.jks: {{ .Values.searchguard.base64Keystore }}
  keypass: {{ .Values.searchguard.base64KeystorePasswd }}
  truststore.jks: {{ .Values.searchguard.base64Truststore }}
  trustpass: {{ .Values.searchguard.base64TruststorePasswd }}
  client-keystore.jks: {{ .Values.searchguard.base64ClientKeystore }}
  root-ca: {{ .Values.searchguard.base64RootCA }}
  admin.crt.pem: {{ .Values.searchguard.base64_client_cert }}
  admin.key.pem: {{ .Values.searchguard.base64_client_key }}
  {{- if (and ( .Values.searchguard.keycloak_auth ) ( .Values.searchguard.base64_keycloak_rootca_pem )) }}
  keycloak-rootca.pem: {{ .Values.searchguard.base64_keycloak_rootca_pem }}
  {{- end }}
{{- end }}

