apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-cmserver
  labels:
    k8s-app: fluent-bit
data:
   fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Plugins_File /fluent-bit/etc/plugins.conf
        Parsers_File /fluent-bit/etc/parser.conf

    [INPUT]
        Name        tail
        Tag         cmserver_cm.*
        Path        /var/log/server/cm.log
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         cmserver_confd.*
        Path        /var/log/confd/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         cmserver_loadNetconf.*
        Path        /var/log/loadNetconf/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         cmserver_start_stop.*
        Path        /var/log/cmserverStartStopLogs/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         cmserver_schemagen.*
        Path        /var/log/schemagen/schemagen.log
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         cmserver_infos.*
        Path        /var/log/infos/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name tail
        Tag conf.*
        Path /var/DebugTrace/EnvoySideCar/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z

    [OUTPUT]
        Name     gstdout
        Match    *

   plugins.conf: |
    [PLUGINS]
        Path   /fluent-bit/lib/out_gstdout.so
