# Default values for EventReceiver.

# Author: Santhi Abraham
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
#

global: 
 imageRegistry: corepaas-docker-local.bhisoj70.apac.nsn-net.net
 imagePullSecrets: 
  name: art-regcred
 casecret: zts1ztssecret
 clustername: "zts1"
 datacenter: "dc1"
 caservicename: caserverservice.default.svc.cluster.local
 metadata_max_release: "19.0"
 metadata_min_release: "0.5"
 vnfname: zts1
 vnfctype: "EFS"
 vnftype: "ZTS"
 counteralarmtracelevel: "error"
envoyports:
  envoyContainerPort: 8080
  envoyContainerProtocol: TCP

countersenv:
  channelbuffsize : 1000

consulmetadata:
  name: eventreceiver
  labels:
    app: eventreceiverapp

consulserver:
   servicename: sdservice

consulenv:
  ztslenvoylbregid: eventreceiver-service # [ eg: ztslenvoylbregid: "lcmserver-service" ]

consulagent:
  service:
    name: sdserviceagent-eventreceiver
    serverservicename: sdservice
    labels:
      app: sdserviceagent-eventreceiver-label
    type: NodePort
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 512Mi
      cpu: 250m


containers:
  consulagentName: consulagent-container

consulagentenv:
  servicedomainName: "svc.cluster.local"
  domainName: "default.svc.cluster.local"
  agentbindip: "0.0.0.0"

Replicas: 2

image:
  eventreceiverimage:
    dockerTag: 1.5.37
    PullPolicy: Always
  fluentbit:
    dockerTag: 1.5.37
    PullPolicy: Always
  envoy:
    dockerTag: 1.5.37
    PullPolicy: Always
  consulregistration:
    dockerTag: 1.5.37
    PullPolicy: Always
  consulimage:
    dockerTag: 1.5.37
    PullPolicy: Always

configmap:
  name: configmapenvoyeventreceiver
  labels:
    app: configmapenvoyeventreceiver-label

ExternalIP: 10.96.77.163

envoyargs:
  - "--config-path /etc/envoy/envoy.json"
  - "--mode serve"
  - "--v2-config-only"


eventreceiver:
  resources:
    requests:
      memory: 16Mi
      cpu: 10m
    limits:
      memory: 4096Mi
      cpu: 2000m

fluentbit:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 2048Mi
      cpu: 500m

envoysidecar:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 4096Mi
      cpu: 1000m

registration:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 256Mi
      cpu: 250m
