{{- if .Values.searchguard.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  root-ca.pem: {{ .Values.searchguard.base64_ca_certificate }}
{{- end }}

