## Image Registry
global:
  registry: "csf-docker-delivered.repo.lab.pl.alcatel-lucent.com"

imageRepo: "lms/citm/citm-default-backend"
imageTag: "4.0.4-5"
imagePullPolicy: IfNotPresent

nodeSelector: {}

runOnEdge: false

tolerations: []

replicaCount: 1

resources:
  requests:
    memory: 10Mi
    cpu: 1m
  limits:
    memory: 64Mi
    cpu: 10m

service:
  clusterIP: ""
  externalIPs: []
  nodePort: ""  
  type: ClusterIP
  servicePort: 8080

backend:
  name: default404
  port: 8080
  debug: "false"
  page:
    title: "404 - Not found"
    body: "The requested page was not found"
    copyright: "Nokia. All rights reserved"
    productFamilyName: "CITM"
    productName: "Default backend"
    productRelease: "4.0.4-5"
    toolbarTitle: "View more ..."
    imageBanner: "Nokia_logo_white.svg"

rbac:
  create: true

istio:
  enable: false

# For helm test
test:
  image: "lms/citm/kubectl"
  tag: "v1.14.8-nano"
  
