apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  - name: metric
    port: 7070
  - name: kubectl
    port: 9090
  selector:
    app: custom-metrics-apiserver