apiVersion: v1
appVersion: 1.0.100
description: This chart is to deploy HCClusterMonitoringService pods in HealthCheckService.
engine: gotpl
maintainers:
- name: Nokia
name: clustermonitoragent
version: 1.0.100
