{{- if (gt (int .Values.server.count) 1) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.podname }}-server-nodes
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: 6379
  selector:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    type: server
{{- end }}
