global:
 imageRegistry: corepaas-docker-local.bhisoj70.apac.nsn-net.net
 imagePullSecrets:
  name: art-regcred
 clustername: "zts1"
 datacenter: "dc1"
 casecret: zts1ztssecret
 esymacip: 127.0.0.1
 esymacport: 8080
#set for false to use emptyDir 
 persistentVolume:
  enabled: true
  
 #Place all dockerTags for subcharts here to ensure eventprocessing service deployment as individual chart

 DestinationType: null
 sftp: true
 splunk: true
 casecret: zts1ztssecret
 clustername: zts1
 ipv6interface: disable
 jobhookenable: true
 jobtimeout: 900
 metadata_max_release: "20"
 metadata_min_release: "2.0"
 postbackup: 0
 postrestore: 0
 prebackup: 0
 prerestore: 0
 terminationGracePeriodSeconds: 30
 vnfname: zts1
 vnftype: ZTS

efsesymac:
  efsmonitor:
    efsmonitor:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 2048Mi
          cpu: 1000m
    fluentbit:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 2048Mi
          cpu: 500m
    envoysidecar:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 4096Mi
          cpu: 1000m
    consulagent:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 512Mi
          cpu: 250m
    registration:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 256Mi
          cpu: 250m
  esymacservice:
    esymachelper:
      resources:
        requests:
          memory: 8Mi
          cpu: 10m
        limits:
          memory: 1024Mi
          cpu: 1000m
    esymacservice:
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 4096Mi
          cpu: 1000m
    cbursidecar:
      resources:
        requests:
          memory: 16Mi
          cpu: 10m
        limits:
          memory: 4096Mi
          cpu: 1000m
    fmesymacagent:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 4096Mi
          cpu: 1000m
    pmesymacagent:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 4096Mi
          cpu: 1000m
    fluentbit:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 2048Mi
          cpu: 500m
    envoysidecar:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 4096Mi
          cpu: 1000m
    consulagent:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 512Mi
          cpu: 250m
    registration:
      resources:
        requests:
          memory: 8Mi
          cpu: 5m
        limits:
          memory: 256Mi
          cpu: 250m

eventdb:
  resources:
    requests:
      memory: 1024Mi
      cpu: 100m
    limits:
      memory: 12288Mi
      cpu: 8000m
    java_heapsize: 4g
    java_newsize: 512m
  admin:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
  cbur:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
  eventdb:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 8192Mi
        cpu: 3000m

  fluentbit:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 2048Mi
        cpu: 500m

  envoysidecar:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 4096Mi
        cpu: 1000m

  consulagent:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 250m

  registration:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 256Mi
        cpu: 250m

eventreceiver:
  eventreceiver:
    resources:
      requests:
        memory: 16Mi
        cpu: 10m
      limits:
        memory: 4096Mi
        cpu: 2000m
  consulagent:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 250m
  fluentbit:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 2048Mi
        cpu: 500m

  envoysidecar:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 4096Mi
        cpu: 1000m

  registration:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 256Mi
        cpu: 250m

resourceManager:
  resourcemanager:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 1024Mi
        cpu: 1000m

  fluentbit:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 2048Mi
        cpu: 500m

  envoysidecar:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 4096Mi
        cpu: 1000m

  consulagent:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 250m

  registration:
    resources:
      requests:
        memory: 8Mi
        cpu: 5m
      limits:
        memory: 256Mi
        cpu: 250m


