# Default values for FMService.
# Author: Venkat Masuldari 
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
#

global:
 imageRegistry: corepaas-docker-local.bhisoj70.apac.nsn-net.net
 imagePullSecrets:
  name: art-regcred
 consulAgentDnsIpInt:
 consulAgentDnsPortInt: 8600 
 consulAgentDnsIp:
 consulAgentDnsPort: 30086
 ExternalDnsIp :
 clustername: "zts1"
 datacenter: "dc1"
 caservicename: caserverservice.default.svc.cluster.local
 metadata_max_release: "19.0"
 metadata_min_release: "0.5"
 vnfname: zts1
 vnfctype: "MDS"
 vnftype: "ZTS"
 casecret: zts1ztssecret
 esymacip: 127.0.0.1
 esymacport: 8080
 counteralarmtracelevel: "error"

countersenv:
  channelbuffsize : 1000

consulagent:
  service:
    name: sdserviceagent-lcm
    serverservicename: sdservice
    labels:
      app: sdserviceagent-lcm-label
    type: NodePort
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 512Mi
      cpu: 250m

consulmetadata:
  name: metatastore 
  labels:
    app: metatastoreapp

containers:
  consulagentName: consulagent-container

consulagentenv:
  servicedomainName: "svc.cluster.local"
  domainName: "default.svc.cluster.local"
  datacenter: "dc1"
  agentbindip: "0.0.0.0"
  severnum: "3"

consulimage:
  repository:  corepaas-docker-local.bhisoj70.apac.nsn-net.net/consul
  dockerTag: 1.5.37
  pullPolicy: IfNotPresent

image:
  metadataimage:
    dockerTag: 1.5.37
    pullPolicy: Always
  envoy:
    dockerTag: 1.5.37
    pullPolicy: Always
  consulregistration:
    dockerTag: 1.5.37
    pullPolicy: Always
  fluentbit:
    dockerTag: 1.5.37
    pullPolicy: Always
  consulimage:
    dockerTag: 1.5.37
    PullPolicy: Always
  cbura:
    dockerTag: 1.5.37
    PullPolicy: Always

imagePullSecrets:
  name: ztsl-helm-registry

configmap:
  name: configmapenvoymetadatastore
  labels:
    app: configmapenvoymetadatastore-label

ExternalIP: 10.96.173.77

config:
  traceLevel: error  

envoyports:
  envoyContainerPort: 8080
  envoyContainerProtocol: TCP

envoyargs:
  - "--config-path /etc/envoy/envoy.json"
  - "--mode serve"
  - "--v2-config-only"


metadatastore:
  resources:
    requests:
      memory: 16Mi
      cpu: 10m
    limits:
      memory: 4096Mi
      cpu: 1000m

fluentbit:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 2048Mi
      cpu: 500m

envoysidecar:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 4096Mi
      cpu: 1000m

registration:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 256Mi
      cpu: 250m

cbursidecar:
  resources:
    requests:
      memory: 16Mi
      cpu: 10m
    limits:
      memory: 4096Mi
      cpu: 1000m