apiVersion: "cbur.bcmt.local/v1"
kind: BrPolicy
metadata:
  name: esymacservice
  labels:
    app: esymacservice-internal-zts1
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: esymacservice-internal-zts1
  volumes:
  - ehdata
  backend:
    mode: AVAMAR
  cronSpec: 0 0 * * *
  k8sType: StatefulSet 
  brOption: 2
  maxiCopy: 2
  hooks:
  - name: esymacservice-internal-zts1
    commands:
      preBackupCmd: ["sh", "-c", "echo preBackupCmd > /tmp/preb.txt"]
      postBackupCmd: ["sh", "-c", "echo post-backup > /tmp/posb.txt" ]
      preRestoreCmd: ["sh", "-c", "echo preRestoreCmd > /tmp/prer.txt"]
      postRestoreCmd: ["sh", "-c", "echo postRestoreCmd > /tmp/posr.txt"]

