apiVersion: v1
kind: ConfigMap
metadata:
  name: fbit-config-eps-efsesymac
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
   fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Plugins_File /fluent-bit/etc/plugins.conf
        Parsers_File /fluent-bit/etc/parser.conf

    [INPUT]
        Name        tail
        Tag         efshelper.*
        Path        /var/log/esymac/**/*
        Path_Key    class
        DB          /var/log/esymac/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/esymac/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
    [INPUT]
        Name        tail
        Tag         efspmclient.*
        Path        /var/log/pm/**/*
        Path_Key    class
        DB          /var/log/pm/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/pm/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
    [INPUT]
        Name        tail
        Tag         efsfmclient.*
        Path        /var/log/fm/**/*
        Path_Key    class
        DB          /var/log/fm/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/fm/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
    [INPUT]
        Name        tail
        Tag         catalinaout.*
        Path        /var/log/catalina.out
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db
    [INPUT]
        Name        tail
        Tag         soapAdapter.*
        Path        /var/log/soapAdapter.log
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db
    [INPUT]
        Name        tail
        Tag         catalina0.*
        Path        /var/log/catalina.0.log
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db
    [INPUT]
        Name        tail
        Tag         efsesymac.*
        Path        /var/log/**/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z

    [INPUT]
        Name        tail 
        Tag         conf.* 
        Path        /var/DebugTrace/EnvoySideCar/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
    [INPUT]
        Name        tail 
        Tag         conf.* 
        Path        /var/log/startup-stderr*.* 
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
    [INPUT] 
        Name        tail 
        Tag         conf.* 
        Path        /var/log/envoy.*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z

    [OUTPUT]
        Name     gstdout
        Match    *


    [FILTER]
        Name     parser
        Match    *
        Parser   epsparser

    [FILTER]
        Name     parser
        Match    system.log
        Parser   cassadraepsparser

    [FILTER]
        Name     parser
        Match    esymachelper.log
        Parser   l4gparser

   plugins.conf: |
    [PLUGINS]
        Path   /fluent-bit/lib/out_gstdout.so

   parser.conf: |
    [PARSER]
        Name        epsparser
        Format      regex
        Regex       (?<log_level>[^:]*): (?<event_time_stamp>.{19}) (?<process_name>([^ ])+):(?<action>[^:]*):(?<log_message>.*) 

    [PARSER]
        Name        cassadraepsparser
        Format      regex
        Regex       (?<log_level>[^ ]*) \[(?<action>[^ ]*)\] (?<event_time_stamp>.{23}) (?<process_name>[^ ]*) (?<log_message>.*)        
 
    [PARSER]
        Name        l4gparser
        Format      regex
        Regex       ^\[(?<logtime>[^\]]*)\] \[(?<loglevel>[^\]]*)\] \((?<action>[^ ]*) (?<process_name>[^\)]*)\)(?<log_message>.*)
