apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.podname }}-vault-config
  labels:
    release: "{{ .Release.Name }}"
data:
  vault_config.hcl: storage "mysql" { address = "secretstore-mariadb.{{ .Release.Namespace }}.svc.cluster.local:3306" ha_enabled = "true" username = "vault" password = "vault" database = "vault" } listener "tcp" { address = "0.0.0.0:8200" tls_key_file = "/opt/vault/tls/tls.key" tls_cert_file="/opt/vault/tls/tls.crt" } disable_mlock = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.podname }}-user-script
  labels:
    release: "{{ .Release.Name }}"
data:
  userscript.sh: |
    #!/usr/bin/env bash
    # Please don't use -e option here to allow the secondsAfterPostInstall option to happen

  {{- with .Values.userScript }}
    echo 'Running custom pre-start script...'
{{ . | indent 4 }}
  {{- end }}

    return "$?"
