apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name.podname }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name.podname }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    chart: {{ .Chart.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # If there're multiple hooks, may define differnent hook-weight value.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.name.podname }}-rolebinding
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ .Values.name.podname }}
    chart: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.podname }}-sa
  namespace: "{{.Release.Namespace}}"
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.name.podname }}-role
  apiGroup: ""

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: "{{.Release.Namespace}}"
  name: {{ .Values.name.podname }}-role
  labels:
    app: {{ .Values.name.podname }}
    chart: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]  
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"] 
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]  
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
