---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.podname }}
  labels:
    app: {{ .Values.name.podname }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }} 
  ports:
  - port: {{ .Values.service.port }} 
    targetPort: skm
    protocol: TCP
  selector:
    app: {{ .Values.name.podname }}
