apiVersion: v1
appVersion: 7.0.1
description: A Kibana Helm chart for Kubernetes
keywords:
- kibana
- data
- log
maintainers:
- email: CSF-BELK@groups.nokia.com
  name: BELK Team
name: belk-kibana
version: 6.0.8
