## ref: https://confluence.app.alcatel-lucent.com/display/plateng/HELM+Application+Deployment+-+LIFECYCLE#HELMApplicationDeployment-LIFECYCLE-RelocatableChart
### global registry
global:
 # This registry is used for fluentd image
 registry: csf-docker-delivered.repo.lab.pl.alcatel-lucent.com
 # This registry is used for kubectl image
 registry1: csf-docker-delivered.repo.lab.pl.alcatel-lucent.com
 seccompAllowedProfileNames: docker/default
 seccompDefaultProfileName: docker/default

#postscalein should be 0 to run postscalein job for cleaning up unused PVCs
postscalein: 0

fluentd:
  kind: StatefulSet
  image:  
    repo: lms/belk-efkc/elk_f
    tag: 1.4.2-19.12.04
  ImagePullPolicy: "IfNotPresent" 
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  securityContext:
    privileged: False
  resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "400m"
      memory: "300Mi"

#set the system name and system ID for non-container log messages
  EnvVars:
    system: "BCMT"
    systemId: "BCMT ID"

# if set to true fluentd container will run as root user and reads container, journal logs.
# setting it to false will run container as td-agent user and it will not read container, journal logs.
# Example- If kind is StatefulSet and you want to store the logs coming from kafka and you dont want to read any container/journal logs then set this flag to false.
# Donot change the flag unless required.
  enable_root_privilege: true
#set enabled as true if you want to add any certificate in fluentd configuration or if you want to use ssl for fluentd configuration while using SG.
#all the fluentd certificates will be present in "/etc/td-agent/certs"
#Make sure to use the same path in fluentd configuration with proper certificate names.
#Give certificate name and paste the base64 converted certificates or passwords in data section.
  fluentd_certificates:
    enabled: false
    data:
      #example
      #prometheus-crt.pem: <base64_root_ca_crt_pem>
      #prometheus-key.pem: <base64_root_ca_key_pem>
      #prometheus-root-ca.pem: <base64_root_ca_pem>
      #es-root-ca.pem: <base64_es_root_ca_pem>

#if you have created certificates in perticular namespace then edit host as elasticsearch.<namespace> in belk.conf present in fluentd-config/ directory
  #configurable values are belk, clog-json, clog-journal, custom-value
  fluentd_config: belk

  configFile: |
    #If you have own configuration for fluentd other than provided by belk/clog then set fluentd_config: custom-value and provide your configuration below. Example-
    #<source>
    #  @type tail
    #  path /var/log/test/*.log
    #  tag test
    #  pos_file /var/log/td-agent.pos
    #  format none
    #</source>
    #<match test>
    #  @type stdout
    #</match>

# set the enabled value to true if some service to be exposed from fluentd like fluentd-promethues-plugin which exports fluentd metrics so that prometheus can scrap the metrics via this service and port
  service:
    enabled: false
    # if you want to provide your own name for service then provide the value in "custom_name"
    # Default value is template {{ "fullname" . }}
    # Delete the old chart and deploy new chart if you want to configure "custom_name" parameter. 
    custom_name: ""
    # type of service: None, ClusterIP
    type: ClusterIP
    # source port for forwarder
    port: 24224
    # metricsPort is for getting fluentd prometheus metrics. 
    # 24231 is the default port of fluentd-prometheus-plugin.
    # If metricsPort is changed, update same port in fluentd-prometheus configuration in the respective .conf file and in the prometheus annotation below as well.
    metricsPort: 24231
    annotations: {}
  # set to false in case of fluentd running as StatefulSet if you dont want to mount these directories.
  volume_mount_enable: true
  # fluentd volumes
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: dockercontainers
      hostPath:
        path: /data0/docker
  # volume mounts
  volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: dockercontainers
      mountPath: /data0/docker
  
  ## Node labels for pod assignment
  ### ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  ## Toleration is asking the K8S schedule to ignore a taint
  ### ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  ## Pod scheduling preferences.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  persistence:
    #For 18.8 BCMT onwards storageClassName cinder will bydefault get picked up. For using the chart in BCMT-18.6 provide storageClassName which you have created.
    ##If you want to use local storage as volume give "local-storage" in storageClassName.
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    # set pvc_auto_delete to true if you want the persistent volume to also get deleted on deletion of the release.
    # This will delete all the previsous data stored in the persistent volume.
    # When local storage is used it will deleted only PVC not PV.
    pvc_auto_delete: false

cbur:
  enabled: true
  #the maximum copy you want to saved.
  maxCopy: 5
  #Modes supported now: "local","NETBKUP","AVAMAR","CEPHS3","AWSS3", case insensitive
  backendMode: "local"
  #It is used for scheduled backup task
  cronJob: "0 23 * * *"
  #Set below parameters to true for auto enabling cron job
  autoEnableCron: false

kubectl:
  image:
    repo: lms/belk-efkc/kubectl
    tag: v1.14.10-nano
  jobResources:
    requests:
     cpu: 200m
     memory: 500Mi
    limits:
     cpu: 1
     memory: 1Gi

