# Default values for EventProcessingService.
# Author: Naveen Kumar T G
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
#

global:
 #imageRegistry: corepaas-docker-local.bhisoj70.apac.nsn-net.net
 imageRegistry: corepaas-docker-local.bhisoj70.apac.nsn-net.net
 imagePullSecrets: 
  name: art-regcred
 casecret: zts1ztssecret
 consulAgentDnsIpInt: 10.254.18.254
 consulAgentDnsPortInt: 8600
 persistentVolume:
  enabled: true
 metadata_max_release: "19.0"
 metadata_min_release: "0.5"
 vnfctype: "EFS" 
 vnfname: "zts1" #to remove
 vnftype: "zts" #to remove
 clustername: "zts1"
 datacenter: "dc1"
 counteralarmtracelevel: "error"

countersenv:
  channelbuffsize : 1000

image:
  resourcemanagerimage:
    dockerTag: 1.5.37
    PullPolicy: IfNotPresent
  fluentbit:
    PullPolicy: IfNotPresent
  envoyimage:
    pullPolicy: IfNotPresent
  initcontainersimage:
    PullPolicy: IfNotPresent
  consul:
    pullPolicy: Always
  consulregistration:
    pullPolicy: Always

pvcStorage:
 resourcemanagerpvc: 2Gi 
configmap:
  name: configmapenvoyresourcemanager
  labels:
    app: configmapenvoyresourcemanager-label

ExternalIP: 10.96.173.96

envoyargs:
  - "--config-path /etc/envoy/envoy.json"
  - "--mode serve"
  - "--v2-config-only"
consulmetadata:
  name: cmserver
  labels:
    app: cmserverapp

consulserver:
 servicename: sdservice

containers:
  consulagentName: consulagent-container

consulagentenv:
  servicedomainName: "svc.cluster.local"
  domainName: "default.svc.cluster.local"
  agentbindip: "0.0.0.0"

consulenv:
  ztslenvoylbregid: resmanager-service


resourcemanager:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 1024Mi
      cpu: 1000m

fluentbit:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 2048Mi
      cpu: 500m

envoysidecar:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 4096Mi
      cpu: 1000m

consulagent:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 512Mi
      cpu: 250m

registration:
  resources:
    requests:
      memory: 8Mi
      cpu: 5m
    limits:
      memory: 256Mi
      cpu: 250m
