{{ if gt (int .Values.global.prerestore) 0 }}
{{- if eq .Values.cluster_type "master-slave" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name.podname }}-prerestore
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "cmdb-admin.labels" . | indent 8 }}
        type: admin
    spec:
      {{- if .Values.rbac_enabled }}
      serviceAccountName: {{ .Values.name.podname }}
      {{- else }}
      securityContext:
        runAsUser: 0
      {{- end }}
      restartPolicy: Never
      containers:
      - name: prerestore-admin
        {{- include "cmdb-admin.image" . | indent 8 }}
        args: [ "restore" ]
        env:
        - name: CLUSTER_TYPE
          value: "{{ .Values.cluster_type }}"
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster_name | default .Release.Name | trunc 32 }}"
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ .Values.name.podname }}
        - name: K8S_PREFIX
          value: {{ .Values.name.podname }}
        - name: HOOK_TYPE
          value: "pre"
        {{- if gt (int .Values.admin.preUpgradeTimeout) 0 }}
        - name: HOOK_TIMEOUT
          value: "{{ .Values.admin.preUpgradeTimeout }}"
        {{- end }}
        {{- if and .Values.admin.debug (gt (int (default '0' .Values.admin.jobDelay)) 0) }}
        - name: HOOK_DELAY
          value: "{{ .Values.admin.jobDelay }}"
        {{- end }}
        {{- include "cmdb-admin.service" . | indent 8 }}
        volumeMounts:
        - name: cluster-cm
          mountPath: /chart
        - name: event-cm
          mountPath: /event
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
      volumes:
      - name: cluster-cm
        configMap:
          name: {{ .Values.name.podname }}-mariadb-cluster
      - name: event-cm
        configMap:
          name: {{ .Values.name.podname }}-admin-event
{{- end }}
{{- end }}
