apiVersion: v1
## CSDC backend (Etcd).
#st-delete-job.yaml
kind: ServiceAccount
metadata:
  name: {{ .Values.name.podname }}-admin
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ .Values.name.podname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # If there're multiple hooks, may define differnent hook-weight value.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.name.podname }}-namespace-admin
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ .Values.name.podname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.podname }}-admin
  namespace: "{{.Release.Namespace}}"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-delete-jobs"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.service.Component }}"
  annotations:
    # This is what defines this resource as a hook. Without this line,
    # the job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.name.podname }}-admin
      containers:
      - name: post-delete-pvc
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.service.kubernetesImage }}:{{ .Values.service.kubernetesTag }}"
        resources:
          limits:
             cpu: {{.Values.service.resources.requests.Cpu }}
             memory: {{.Values.service.resources.requests.Memory }}
          requests:
            cpu: {{ .Values.service.resources.requests.Cpu }}
            memory: {{ .Values.service.resources.requests.Memory }}
        {{- if not .Values.service.preserve_pvc }}
        command:
          - "/bin/sh"
          - "-c"
          - kubectl delete pvc --namespace {{ .Release.Namespace }} -l app={{ .Values.name.podname }}
        {{- end }}
