apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name.podname }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name.podname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
