{{- if .Values.service.tls -}}
{{- if .Values.service.user_defined_tls -}}
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-user-ca-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.pem: {{ .Values.service.user_defined_ca | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-ca-cert-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "tls/ca-cert/*").AsSecrets | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-client-cert-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  client.pem: {{ .Values.service.user_defined_client_cert | b64enc | quote }}  
  client-key.pem: {{ .Values.service.user_defined_client_key  | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-server-cert-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  server.pem: {{ .Values.service.user_defined_server_cert | b64enc | quote }}  
  server-key.pem: {{ .Values.service.user_defined_server_key  | b64enc | quote }}

---

{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-ca-cert-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "tls/ca-cert/*").AsSecrets | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-client-cert-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "tls/client-cert/*").AsSecrets | indent 2 }}

---
{{- end -}}
{{- end -}}

{{- if .Values.service.RBAC -}}
apiVersion: v1
kind: Secret
metadata:
  name: "sdc-rbac-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rbac: {{ randAlphaNum 32 | b64enc | quote }}

{{- end -}}
