{{ if gt (int .Values.global.postheal ) 0 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name.podname }}-postheal
  labels:
    {{- include "cmdb-admin.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "cmdb-admin.labels" . | indent 8 }}
        type: admin
    spec:
      restartPolicy: Never
      containers:
      - name: postheal-admin
        {{- include "cmdb-admin.image" . | indent 8 }}
        args: [ "heal" ]
        env:
        - name: CLUSTER_TYPE
          value: "{{ .Values.cluster_type }}"
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster_name | default .Release.Name | trunc 32 }}"
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ .Values.name.podname }}
        - name: K8S_PREFIX
          value: {{ .Values.name.podname }}
        - name: HOOK_TYPE
          value: "post"
        {{- if gt (int .Values.admin.postUpgradeTimeout) 0 }}
        - name: HOOK_TIMEOUT
          value: "{{ .Values.admin.postUpgradeTimeout }}"
        {{- end }}
        {{- if and .Values.admin.debug (gt (int (default '0' .Values.admin.jobDelay)) 0) }}
        - name: HOOK_DELAY
          value: "{{ .Values.admin.jobDelay }}"
        {{- end }}
        {{- include "cmdb-admin.service" . | indent 8 }}
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
        volumeMounts:
        - name: cluster-cm
          mountPath: /chart
      volumes:
      - name: cluster-cm
        configMap:
          name: {{ .Values.name.podname }}-mariadb-cluster
{{ end }}
