apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.backend.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: "{{ .Values.backend.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.backend.name }}
          image: "{{ .Values.global.registry }}/{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: DEFAULT_BACKEND_TITLE
              value: "{{ .Values.backend.page.title }}"
            - name: DEFAULT_BACKEND_BODY
              value: "{{ .Values.backend.page.body }}"
            - name: DEFAULT_BACKEND_COPYRIGHT
              value: "{{ .Values.backend.page.copyright }}"
            - name: DEFAULT_BACKEND_PRODUCT_FAMILY_NAME
              value: "{{ .Values.backend.page.productFamilyName }}"
            - name: DEFAULT_BACKEND_PRODUCT_NAME
              value: "{{ .Values.backend.page.productName }}"
            - name: DEFAULT_BACKEND_RELEASE
              value: "{{ .Values.backend.page.productRelease }}"
            - name: DEFAULT_BACKEND_TOOLBAR_TITLE
              value: "{{ .Values.backend.page.toolbarTitle }}"
            - name: DEFAULT_BACKEND_IMAGE_BANNER
              value: "{{ .Values.backend.page.imageBanner }}"
            - name: DEFAULT_BACKEND_DEBUG
              value: "{{ .Values.backend.debug }}"
            - name: DEFAULT_BACKEND_PORT
              value: "{{ .Values.backend.port }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
              scheme: HTTP
            initialDelaySeconds: 7
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 5
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
{{- if .Values.runOnEdge }}
        is_edge: 'true'
{{- end }}
    {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 2
