apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.backend.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
