# values-model.yaml

type: object
properties:
    resources:
        description: |
            Model of configuration required to request new instances
                 of CITM Ingress
        type: object
        properties:
            memory:
                description: |
                     Memory size reserved for a service.
                type: string
                default: 256Mi
            cpu:
               description: |
                    CPU resources reserved for a service.
               type: string
               default: 250m

