{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "eventdb.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "eventdb.fullname" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['']
  resources:
  - pods
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['']
  resources:
  - services
  - endpoints
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
- nonResourceURLs: ["/version", "/version/*"]
  verbs: ['get']
- apiGroups: ['']
  resources:
  - nodes
  verbs: ['list', 'watch']
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['list']
{{- end }}
