apiVersion: v1
kind: Service
metadata:
  name: {{ template "eventdb.fullname" . }}
  labels:
    app: {{ template "eventdb.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if and .Values.metrics.enabled .Values.metrics.annotate_service .Values.metrics.annotations }}
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
{{- end }}

spec:
  type: {{ .Values.service.type }}
  {{- if and (eq "ClusterIP" .Values.service.type) (.Values.service.clusterIP) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
   - name: cql
     port: {{ default 9042 .Values.config.ports.cql }}
     targetPort: {{ default 9042 .Values.config.ports.cql }}
   - name: intra-node
     port: 7000
   - name: jmx
     port: 7199
  selector:
    app: {{ template "eventdb.fullname" . }}
