{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "eventdb.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "eventdb.fullname" . }}
{{- end }}
