---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "config-crdb-redisio.fullname" . }}-cluster-config
  labels:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
data:
  cluster.env: |-
    # Environment variables for cluster configuration
    SERVER_COUNT={{ .Values.server.count }}
    SERVER_NODE_SERVICE={{ template "config-crdb-redisio.fullname" . }}-server-nodes
    SERVER_NODE_PREFIX={{ template "config-crdb-redisio.fullname" . }}-server
  {{- if and .Values.sentinel .Values.sentinel.enabled }}
    SENTINEL_COUNT={{ .Values.sentinel.count }}
    SENTINEL_NODE_SERVICE={{ template "config-crdb-redisio.fullname" . }}-sentinel-nodes
    SENTINEL_NODE_PREFIX={{ template "config-crdb-redisio.fullname" . }}-sentinel
    SENTINEL_QUORUM={{ .Values.sentinel.quorum }}
  {{- end }}
