apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "config-crdb-redisio.fullname" . }}-post-delete
  labels:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.admin.hookDeletePolicy | quote }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "config-crdb-redisio.common_labels" . | indent 8 }}
        type: admin
    spec:
      securityContext:
        runAsUser: 6379
        runAsGroup: 6379
        fsGroup: 6379
      {{- if .Values.rbacEnabled }}
      serviceAccountName: {{ template "config-crdb-redisio.fullname" . }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: post-delete-admin
        {{- include "config-crdb-redisio.admin.image" . | indent 8 }}
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
        args: [ "delete" ]
        env:
        - name: GROUP_NAME
          value: configmaster
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ template "config-crdb-redisio.fullname" . }}
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_PREFIX
          value: {{ template "config-crdb-redisio.fullname" . }}
        - name: HOOK_TYPE
          value: "post"
        - name: PRESERVE_PVC
          value: {{ .Values.global.persistentVolume.preservePvc | quote }}
        - name: RBAC_ENABLED
          value: {{ .Values.rbacEnabled | quote }}
        - name: DEBUG
          value: {{ quote (.Values.admin.debug | default "") }}
