---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "config-crdb-redisio.fullname" . }}-redis-secrets
  labels:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-delete-policy": hook-failed
type: Opaque
data:
  {{- if .Values.common.password }}
    {{- if eq .Values.common.password "none" }}
  redis-password: ""
    {{- else }}
  redis-password: {{ .Values.common.password | quote }}
    {{- end }}
  {{- else }}
  redis-password: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
