---
apiVersion: v1
kind: Service
metadata:
  name: configmaster
  labels:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.services.redis.type }}
  ports:
  - name: redis
    port: {{ .Values.services.redis.port }}
    targetPort: 6379
    {{- if and (eq .Values.services.redis.type "NodePort") .Values.services.redis.nodePort }}
    nodePort: {{ .Values.services.redis.nodePort }}
    {{- end }}
  selector:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    type: server
    redisio_role: master
---
{{- if gt (int .Values.server.count) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: configmaster-readonly
  labels:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.services.redis.type }}
  ports:
  - name: redis
    port: {{ .Values.services.redis.port }}
    targetPort: 6379
    {{- if and (eq .Values.services.redis.type "NodePort") .Values.services.redis.nodePortReadOnly }}
    nodePort: {{ .Values.services.redis.nodePortReadOnly }}
    {{- end }}
  selector:
    {{- include "config-crdb-redisio.common_labels" . | indent 4 }}
    type: server
    redisio_role: slave
{{- end }}