---
{{- if and (.Values.admin.postInstall | default "") (.Values.admin.postInstall.enabled | default "") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cm-crdb-redisio.fullname" . }}-post-install
  labels:
    {{- include "cm-crdb-redisio.common_labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.admin.hookDeletePolicy | quote }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "cm-crdb-redisio.common_labels" . | indent 8 }}
        type: admin
    spec:
      securityContext:
        runAsUser: 6379
        runAsGroup: 6379
        fsGroup: 6379
      {{- if .Values.rbacEnabled }}
      serviceAccountName: {{ template "cm-crdb-redisio.fullname" . }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: post-install-admin
        {{- include "cm-crdb-redisio.admin.image" . | indent 8 }}
        resources:
          requests:
            memory: {{ .Values.admin.resources.requests.memory }}
            cpu: {{ .Values.admin.resources.requests.cpu }}
          limits:
            memory: {{ .Values.admin.resources.limits.memory }}
            cpu: {{ .Values.admin.resources.limits.cpu }}
        args: [ "install" ]
        env:
        - name: GROUP_NAME
          value: "cmmaster"
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: K8S_LABELS
          value: app={{ template "cm-crdb-redisio.fullname" . }}
        - name: K8S_PREFIX
          value: {{ template "cm-crdb-redisio.fullname" . }}
        - name: HOOK_TYPE
          value: "post"
        - name: PRESERVE_PVC
          value: {{ .Values.global.persistentVolume.preservePvc | quote }}
        - name: RBAC_ENABLED
          value: {{ .Values.rbacEnabled | quote }}
        - name: DEBUG
          value: {{ quote ( .Values.admin.debug | default "" ) }}
        volumeMounts:
        - name: cluster-cm
          mountPath: /cluster
      volumes:
      - name: cluster-cm
        configMap:
          name: {{ template "cm-crdb-redisio.fullname" . }}-cluster-config
{{- end }}
