---

apiVersion: v1
kind: Service
metadata:
  name: cmmaster-sentinel
  labels:
    {{- include "cm-crdb-redisio.common_labels" . | indent 4 }}
spec:
  type: {{ .Values.services.sentinel.type }}
  ports:
  - name: sentinel
    port: {{ .Values.services.sentinel.port }}
    targetPort: 26379
    {{- if and (eq .Values.services.sentinel.type "NodePort") .Values.services.sentinel.nodePort }}
    nodePort: {{ .Values.services.sentinel.nodePort }}
    {{- end }}
  selector:
    {{- include "cm-crdb-redisio.common_labels" . | indent 4 }}
    type: sentinel