apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapenvoydscli
  labels:
    app: configmapenvoydscli-label
    chart: {{ template "datasync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  envoy.yaml: |-
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
          protocol: TCP
    stats_flush_interval:
      seconds: 5
    static_resources:
      listeners:
      - name: app1  ######################################## dsserver to dsreader ##########################################################
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8081
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: app1
              route_config:
                name: app1
                virtual_hosts:
                - name: app1
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dsserver
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: app1
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                 path: "/var/DebugTrace/EnvoySideCar/envoydsserver.log"
              generate_request_id: true

      - name: app
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8888
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: app
              route_config:
                name: app
                virtual_hosts:
                - name: app
                  domains:
                  - "*"
                  routes:
                  - match:    ######################################## logreceiver ##########################################################
                      prefix: "/nokia_ztsl_EventProcessingService_v1.EventProviderService" #need to modify
                    route:
                      cluster: logreceiver
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: app
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                  path: "/var/DebugTrace/EnvoySideCar/envoylogreceiver.log"
              generate_request_id: true

      - name: appeps
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 6061
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: app
              route_config:
                name: appeps
                virtual_hosts:
                - name: appeps
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: epsserver ######################################## eps route addition for alarms ##########################################################
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: appeps
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                 path: "/var/DebugTrace/EnvoySideCar/envoyepsserver.log"
              generate_request_id: true               

      - name: umservice
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 9090
            protocol: TCP
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: umservice
              cluster: umserver
              access_log:
                name: envoy.file_access_log
                config:
                 path: "/var/DebugTrace/EnvoySideCar/envoyumservice.log"
      - name: dsclisshapp
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 6060
            protocol: TCP
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: dsclisshapp
              cluster: dsclissh
              access_log:
                name: envoy.file_access_log
                config:
                 path: "/var/DebugTrace/EnvoySideCar/envoydscli.log"

      clusters:

      - name: dsserver ######################################## dsserver to dscli ##########################################################
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: dsserver-service-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
         common_tls_context:
          tls_params:
            tls_minimum_protocol_version: "TLSv1_2"
          tls_certificates:
          - certificate_chain:
              filename: "/certs/cert.pem"
            private_key:
              filename: "/certs/key.pem"
          validation_context:
            trusted_ca:
              filename: "/certs/cacert.pem"

        http2_protocol_options: {}


      - name: umserver
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: umserver-service-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8002
            protocol: TCP

      - name: logreceiver ######################################## logreceiver ##########################################################
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: logreceiver-service-{{ .Values.global.clustername }}.service.{{ .Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
            tls_certificates:
            - certificate_chain:
                filename: "/certs/cert.pem"
              private_key:
                filename: "/certs/key.pem"
            validation_context:
              trusted_ca:
                filename: "/certs/cacert.pem"
        http2_protocol_options: {}

      - name: epsserver
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: eventreceiver-service-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
         common_tls_context:
          tls_params:
            tls_minimum_protocol_version: "TLSv1_2"         
          tls_certificates:
          - certificate_chain:
              filename: "/certs/cert.pem"
            private_key:
              filename: "/certs/key.pem"
          validation_context:
            trusted_ca:
              filename: "/certs/cacert.pem"
        http2_protocol_options: {}
      - name: dsclissh 
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 2024
            protocol: TCP
