apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapenvoydsreader
  labels:
    app: configmapenvoydsreader-label
    chart: {{ template "datasync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  envoy.yaml: |-
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
          protocol: TCP
    stats_flush_interval:
      seconds: 5
    static_resources:
      listeners:
      - name: appdsserver  ######################################## dsserver ##########################################################
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8081
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: appdsserver
              route_config:
                name: appdsserver
                virtual_hosts:
                - name: appdsserver
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dsserver
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: appdsserver
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                  path: "/var/DebugTrace/EnvoySideCar/envoydsserver.log"
              generate_request_id: true

      - name: appeps
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 6061
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: app
              route_config:
                name: appeps
                virtual_hosts:
                - name: appeps
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: epsserver ######################################## eps route addition for alarms ##########################################################
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: appeps
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                  path: "/var/DebugTrace/EnvoySideCar/envoyeps.log"
              generate_request_id: true                


      - name: appdsreader 
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
            protocol: TCP
        filter_chains:
        - tls_context:
            common_tls_context:
              tls_params:
                tls_minimum_protocol_version: "TLSv1_2"
              tls_certificates:
              - certificate_chain:
                  filename: "/certs/cert.pem"
                private_key:
                  filename: "/certs/key.pem"
              validation_context:
                trusted_ca:
                  filename: "/certs/cacert.pem"
              alpn_protocols: h2,http/1.1
            require_client_certificate: true
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: appdsreader
              stream_idle_timeout: 0s
              route_config:
                name: appdsreader
                virtual_hosts:
                - name: appdsreader
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dsreader ######################################## dsreader##########################################################
                      max_grpc_timeout : "0.000s"
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: appdsreader                      
                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                  path: "/var/DebugTrace/EnvoySideCar/envoydsreader.log"
              generate_request_id: true 

      - name: app 
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8888
            protocol: TCP
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: app
              stream_idle_timeout: 0s
              route_config:
                name: app
                virtual_hosts:
                - name: app
                  domains:
                  - "*"
                  routes:
                  - match:    ######################################## logreceiver ########################################################## 
                      prefix: "/nokia_ztsl_EventProcessingService_v1.EventProviderService" #need to modify
                    route:
                      cluster: logreceiver
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: app
                  - match: ################################ configservice ##############################
                      prefix: "/nokia.ztsl.config.v1.Config/"
                    route:
                      cluster: configservice
                      max_grpc_timeout : "0.000s"
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: app
                  - match: ################################ configservice ##############################
                      prefix: "/grpc.health.v1.Health/"
                    route:
                      cluster: configservice
                      max_grpc_timeout : "0.000s"
                      timeout:
                        seconds: 1800
                    decorator:
                      operation: app

                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              tracing:
                operation_name: INGRESS
              server_name: envoy-ingress-app
              idle_timeout:
                seconds: 1800
              drain_timeout:
                seconds: 1800
              access_log:
                name: envoy.file_access_log
                config:
                  path: "/var/DebugTrace/EnvoySideCar/envoyconfigservice.log"
              generate_request_id: true                           

      clusters:

      - name: dsserver ######################################## dsserver to dsreader ##########################################################
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: dsserver-service-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
            tls_certificates:
            - certificate_chain:
                filename: "/certs/cert.pem"
              private_key:
                filename: "/certs/key.pem"
            validation_context:
              trusted_ca:
                filename: "/certs/cacert.pem"
        http2_protocol_options: {}

      - name: dsreader ######################################## dsreader ##########################################################
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 20003
            protocol: TCP
        http2_protocol_options: {} 

      - name: logreceiver ######################################## logreceiver ########################################################## 
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: logreceiver-service-{{ .Values.global.clustername }}.service.{{ .Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
            tls_certificates:
            - certificate_chain:
                filename: "/certs/cert.pem"
              private_key:
                filename: "/certs/key.pem"
            validation_context:
              trusted_ca:
                filename: "/certs/cacert.pem"
        http2_protocol_options: {}

      - name: epsserver
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: eventreceiver-service-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
            tls_certificates:
            - certificate_chain:
                filename: "/certs/cert.pem"
              private_key:
                filename: "/certs/key.pem"
            validation_context:
              trusted_ca:
                filename: "/certs/cacert.pem"
        http2_protocol_options: {}

      - name: configservice ######################################## configservice ########################################################## 
        type: STRICT_DNS
        connect_timeout:
          seconds: 1800
        lb_policy: ROUND_ROBIN
        dns_resolvers:
        - socket_address:
            address: 127.0.0.1
            port_value: 8600
            protocol: UDP
        hosts:
        - socket_address:
            address: configserverservice-{{.Values.global.clustername}}.service.{{.Values.global.datacenter }}
            port_value: 8080
            protocol: TCP
        tls_context:
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
            tls_certificates:
            - certificate_chain:
                filename: "/certs/cert.pem"
              private_key:
                filename: "/certs/key.pem"
            validation_context:
              trusted_ca:
                filename: "/certs/cacert.pem"
        http2_protocol_options: {}
