apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-dscli
  labels:
    k8s-app: fluent-bit
data:
   fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Plugins_File /fluent-bit/etc/plugins.conf
        Parsers_File /fluent-bit/etc/parser.conf

    [INPUT]
        Name        tail
        Tag         dscli.*
        Path        /var/log/cli/dscli.log
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name        tail
        Tag         dscli_sshd.*
        Path        /var/log/sshdStartStopLogs/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 5M

    [INPUT]
        Name tail
        Tag conf.*
        Path /var/DebugTrace/EnvoySideCar/*
        Path_Key    class
        DB          /var/log/{{ .Chart.Name }}_{{ randAlphaNum 5 | lower }}_DbFile.db
        Exclude_Path /var/log/*.db,*.gz,*.tar,*.zip,*.bz2,*.xz,*.7z

    [OUTPUT]
        Name     gstdout
        Match    *


   plugins.conf: |
    [PLUGINS]
        Path   /fluent-bit/lib/out_gstdout.so
