{{- if .Values.fluentd.fluentd_certificates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }}
type: Opaque
data:
{{ toYaml .Values.fluentd.fluentd_certificates.data | indent 2 }}
{{- end}}
