apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-sa-admin
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-8"
    # hhok-failed is not working so using before-hook-creation
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: {{ .Values.global.seccompAllowedProfileNames }}
    seccomp.security.alpha.kubernetes.io/defaultProfileName: {{ .Values.global.seccompDefaultProfileName }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-rolebinding
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: {{ .Values.global.seccompAllowedProfileNames }}
    seccomp.security.alpha.kubernetes.io/defaultProfileName: {{ .Values.global.seccompDefaultProfileName }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-sa-admin
  namespace: "{{.Release.Namespace}}"
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ template "fullname" . }}-role
  apiGroup: ""

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: "{{.Release.Namespace}}"
  name: {{ template "fullname" . }}-role
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: {{ .Values.global.seccompAllowedProfileNames }}
    seccomp.security.alpha.kubernetes.io/defaultProfileName: {{ .Values.global.seccompDefaultProfileName }}
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
---
{{- if .Values.fluentd.persistence.pvc_auto_delete }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-delete-pvc-job
  labels:
    app: {{ template "name" . }}
  annotations:
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: {{ .Values.global.seccompAllowedProfileNames }}
    seccomp.security.alpha.kubernetes.io/defaultProfileName: {{ .Values.global.seccompDefaultProfileName }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
      serviceAccountName: {{ template "fullname" . }}-sa-admin
      restartPolicy: Never
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/local/bin/kubectl
      containers:
      - name: post-delete-pvc
        image: "{{ .Values.global.registry1 }}/{{ .Values.kubectl.image.repo }}:{{ .Values.kubectl.image.tag }}"
        resources:
{{ toYaml .Values.kubectl.jobResources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
             drop:
              - all
        volumeMounts:
        - name: kubectl
          mountPath: /kubectl
        command:
        - sh
        - "-c"
        - |
          kubectl delete pvc --namespace {{ .Release.Namespace }} -l k8s-app={{ template "fullname" . }}-es
---
{{- end }}

