{{- if .Values.cbur.enabled }}
apiVersion: "cbur.bcmt.local/v1"
kind: BrPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  k8sobjects:
  - object-type: configmaps
    match-criteria: name
    match-string: {{ .Release.Name }}-belk-kibana
  backend:
    mode: "{{ .Values.cbur.backendMode }}"
  cronSpec: "{{ .Values.cbur.cronJob }}"
  autoEnableCron: {{ .Values.cbur.autoEnableCron }}
  maxiCopy: {{ .Values.cbur.maxCopy }}
  k8sType: deployment
  hooks:
  - name: kibana
    commands:
      preBackupCmd: []
      postBackupCmd: []
      preRestoreCmd: []
      postRestoreCmd: []
{{- end}}
