{{- if .Values.searchguard.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  kibana_es_username: {{ .Values.searchguard.base64_kib_es_username }}
  kibana_es_password: {{ .Values.searchguard.base64_kib_es_password }}
  root-ca.pem: {{ .Values.searchguard.base64_ES_RootCA }}
  kibana.crt.pem: {{ .Values.searchguard.base64ServerCrt }}
  kibana.key.pem: {{ .Values.searchguard.base64ServerKey }}
  {{- if .Values.searchguard.keycloak_auth }}
  keycloak-root-ca.pem: {{ .Values.searchguard.base64_keycloak_rootca_pem}}
  {{- end }}
{{- end }}

{{- if and .Values.sane .Values.searchguard.keycloak_auth}}
---
apiVersion: v1
kind: Secret
metadata:
  name: csan-{{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  keycloak_admin_username: {{ .Values.sane.keycloak_admin_user_name }}
  {{- if .Values.sane.keycloak_admin_password }}
  keycloak_admin_password: {{ .Values.sane.keycloak_admin_password }}
  {{- end }}
  {{- if .Values.sane.keycloak_sane_user_password }}
  sane_user_password: {{ .Values.sane.keycloak_sane_user_password }}
  {{- end }}
{{- end }}
