{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: "{{ printf "%s.%s.%.0f" .Release.Namespace .Release.Name .Values.kibana.port}}"
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.ingress.tls }}
 tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
 rules:
 {{- if .Values.ingress.host }}
 - host: {{ .Values.ingress.host }}
   http:
     paths:
     - backend:
         {{- if .Values.service.name }}
         serviceName: {{ .Values.service.name }}
         {{- else }}
         serviceName: {{ template "fullname" . }}
         {{- end }}
         servicePort: {{ .Values.kibana.port }}
       path: {{ .Values.kibanabaseurl.url }}{{ .Values.kibanabaseurl.cg }}
 {{- else }}
 - http:
     paths:
     - backend:
         {{- if .Values.service.name }}
         serviceName: {{ .Values.service.name }}
         {{- else }}
         serviceName: {{ template "fullname" . }}
         {{- end }}
         servicePort: {{ .Values.kibana.port }}
       path: {{ .Values.kibanabaseurl.url }}{{ .Values.kibanabaseurl.cg }}
 {{- end }}
{{- end }}
