---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.podname }}-cluster-config
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
data:
  cluster.env: |-
    # Environment variables for cluster configuration
    SERVER_COUNT={{ .Values.server.count }}
    SERVER_NODE_SERVICE={{ .Values.name.podname }}-server-nodes
    SERVER_NODE_PREFIX={{ .Values.name.podname }}-server
  {{- if and .Values.sentinel .Values.sentinel.enabled }}
    SENTINEL_COUNT={{ .Values.sentinel.count }}
    SENTINEL_NODE_SERVICE={{ .Values.name.podname }}-sentinel-nodes
    SENTINEL_NODE_PREFIX={{ .Values.name.podname }}-sentinel
    SENTINEL_QUORUM={{ .Values.sentinel.quorum }}
  {{- end }}
