{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name.podname }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
  verbs: ["get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "patch", "update", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.name.podname }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded, hook-failed"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name.podname }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": "hook-succeeded, hook-failed"
rules:
- apiGroups: [""]
  resources: ["configmaps", "persistentvolumeclaims", "secrets"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": "hook-succeeded, hook-failed"
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.podname }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.name.podname }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
