---
{{- if (and .Values.sentinel.enabled (gt (int .Values.server.count) 1)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crdb-redisio.groupname" . }}-sentinel
  labels:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.services.sentinel.type }}
  ports:
  - name: sentinel
    port: {{ .Values.services.sentinel.port }}
    targetPort: 26379
    {{- if and (eq .Values.services.sentinel.type "NodePort") .Values.services.sentinel.nodePort }}
    nodePort: {{ .Values.services.sentinel.nodePort }}
    {{- end }}
  selector:
    {{- include "crdb-redisio.common_labels" . | indent 4 }}
    type: sentinel
{{- end }}